### ISSUE TITLE
Error regarding Pagination  while exporting Testimonial.jsx file

### ISSUE THREAD

**Issue by kbhavre** [kbhavre/Doctor_Appointment_Booking#1]
![Screenshot 2023-10-05 232626](https://github.com/kbhavre/Doctor_Appointment_Booking/assets/89301840/dbe65e15-f0bf-4e7e-9a8f-4f94e8804801)

**Comment by Ronit-gurjar** [comment]
![image](https://github.com/kbhavre/Doctor_Appointment_Booking/assets/92150685/1d55d37c-4525-4347-a29a-d79f04a67dc6)

>[!NOTE]
> 1. The issue is regarding import in `Testimonial.jsx` at line 2
> 1. your import statement is wrong...replace 'swiper' with 'swiper/module'
> 1. [Reference](https://swiperjs.com/react)
