### ISSUE TITLE
Not able to open Login page

### ISSUE THREAD

**Issue by kbhavre** [kbhavre/Doctor_Appointment_Booking#4]
on clicking the login button , if the user already have an account then it should ask for the login details instead of signup details

**Comment by kbhavre** [comment]
It might be a navigation issue

**Comment by devham236** [comment]
hey @kbhavre, i would love to work on this issue

**Comment by ayushp0413** [comment]
Assign issue to me (Login Signup Router)

**Comment by kbhavre** [comment]
Issue fixed , great work @ayushp0413
